export interface ActionProps<T = any> {
    type: string
    payload?: T
}

export enum STATISTICS {
    GET_STATISTICS = 'STATISTICS/GET_STATISTICS',
    SET_FILTER = 'STATISTICS/SET_FILTER',
    SET_RESULT = 'STATISTICS/SET_RESULT',
}

export enum AUTH {
    SET_TOKEN = 'AUTH/SET_TOKEN',
    CLEAR_TOKEN = 'AUTH/CLEAR_TOKEN',
}

export enum PROFILE {
    GET_PROFILE = 'PROFILE/GET_PROFILE',
    SET_PROFILE = 'PROFILE/SET_PROFILE',
    EDIT_PROFILE = 'PROFILE/EDIT_PROFILE',
    GET_CODE = 'PROFILE/GET_CODE',
    EDIT_PASSWORD = 'PROFILE/EDIT_PASSWORD',
    SET_PASSWORD = 'PROFILE/SET_PASSWORD',
}

export enum CLASSIFIER {
    GET_SEX = 'CLASSIFIER/GET_SEX',
    SET_SEX = 'CLASSIFIER/SET_SEX',
    GET_LEVEL_CAREER = 'CLASSIFIER/GET_LEVEL_CAREER',
    SET_LEVEL_CAREER = 'CLASSIFIER/SET_LEVEL_CAREER',
}

export enum SNACKBAR {
    SHOW_SNACKBAR = 'SHOW_SNACKBAR',
    HIDE_SNACKBAR = 'HIDE_SNACKBAR',
}
